[env:esp32-c6-devkitc-1]
platform  = espressif32
board     = esp32-c6-devkitc-1
framework = espidf

; ESP-IDF sdkconfig overrides (OpenThread + CoAP)
board_build.cmake_extra_args =
    -DSDKCONFIG_DEFAULTS=${PROJECT_DIR}/sdkconfig.defaults

; Serial monitor
monitor_speed = 115200
